name: Bug Report
description: Found something you weren't expecting? Report it here!
labels: kind/bug
body:
  - type: markdown
    attributes:
      value: |
        NOTE: If your issue is a security concern, please send an email to security@vikunja.io instead of opening a public issue.
  - type: markdown
    attributes:
      value: |
        Please fill out this issue template to report a bug.
        
        1. If you want to propose a new feature, please open a discussion thread in the forum: https://community.vikunja.io
        2. Please ask questions or configuration/deploy problems on our [Matrix Room](https://matrix.to/#/#vikunja:matrix.org) or forum (https://community.vikunja.io).
        3. Make sure you are using the latest release and
           take a moment to check that your issue hasn't been reported before.
        4. Please give all relevant information below for bug reports, because
           incomplete details will be handled as an invalid report and closed.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a description of your issue here, with a URL if you were able to reproduce the issue (see below).
  - type: input
    id: frontend-version
    attributes:
      label: Vikunja Frontend Version
      description: Vikunja frontend version (or commit reference) of your instance
    validations:
      required: true
  - type: input
    id: api-version
    attributes:
      label: Vikunja API Version
      description: Vikunja API version (or commit reference) of your instance
    validations:
      required: true
  - type: input
    id: browser-version
    attributes:
      label: Browser and version
      description: If your issue is related to a frontend problem, please provide the browser and version you used to reproduce it.
  - type: dropdown
    id: can-reproduce
    attributes:
      label: Can you reproduce the bug on the Vikunja demo site?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If this issue involves the Web Interface, please provide one or more screenshots
